// SPDX-License-Identifier: GPL-2.0-or-later
// Pixel-edge coordinates; the viewport is the native Saturn render target size.
void main(float2 position : POSITION, float2 uv : TEXCOORD0,
          uniform float2 viewport_size,
          out float4 clip_position : POSITION, out float2 texcoord : TEXCOORD0)
{
    clip_position = float4(position.x * (2.0 / viewport_size.x) - 1.0,
                           1.0 - position.y * (2.0 / viewport_size.y), 0.0, 1.0);
    texcoord = uv;
}
