// SPDX-License-Identifier: GPL-2.0-or-later
// Shared C/Cg expression so the exact arithmetic receives a bounded host test.
// Inputs: renderer pixel coordinates within +/-4096; mosaic size 1..16.
int cell(int coordinate, int size) {
  int q = (int)((float)coordinate/(float)size);
  int remainder = coordinate-q*size;
  if (coordinate >= 0) {
    if (remainder < 0) --q;
    else if (remainder >= size) ++q;
  } else {
    if (remainder > 0) ++q;
    else if (remainder <= -size) --q;
  }
  return q*size;
}
