// SPDX-License-Identifier: GPL-2.0-or-later
// Native form of Yglprg_normal_v. Keep upstream row-vector matrix convention.
// glUniformMatrix4fv(GL_FALSE) supplies column-major coefficients; Cg defaults
// to row-major (Sony Shader Compiler User's Guide, matrix storage ordering).
uniform column_major float4x4 u_mvpMatrix;
void main(float4 a_position : POSITION, float4 a_texcoord : TEXCOORD0,
          out float4 position : POSITION, out float4 v_texcoord : TEXCOORD0) {
  position = mul(a_position, u_mvpMatrix);
  v_texcoord = a_texcoord;
}
