// SPDX-License-Identifier: GPL-2.0-or-later
// CPU-generated rotation image and coefficient-selected line color share atlas.
#include "packed_texture.h"
uniform sampler2D s_texture, s_color, s_line_texture;
uniform float2 u_texsize;
uniform float4 u_color_offset;
uniform int u_blendmode;
float4 palette(int index) {
  return tex2D(s_color, float2((float(index) + 0.5) / 2048.0, 0.5));
}
float4 main(float4 v_texcoord : TEXCOORD0) : COLOR {
  float4 code = tex2D(s_texture, (float2(int2(v_texcoord.xy)) + 0.5) / u_texsize);
  if (code.a == 0.0) discard;
  int high = YglUnorm8(code.g);
  float4 color = palette(((high & 0x7f) << 8) | YglUnorm8(code.r));
  color.a = code.a;
  if ((high & 0x80) != 0) {
    int coefficient = YglUnorm8(code.b);
    float4 linecode = tex2D(s_line_texture,
                           (float2(int2(v_texcoord.zw)) + 0.5) / u_texsize);
    int index = ((YglUnorm8(linecode.g) & 0x7f) << 8) | YglUnorm8(linecode.r);
    if ((coefficient & 0x80) != 0)
      index = (index & 0x780) | (coefficient & 0x7f);
    float4 linecolor = palette(index);
    if (u_blendmode == 1) {
      color = lerp(color, linecolor, 1.0 - code.a);
      color.a = code.a + 0.25;
    } else if (u_blendmode == 2) {
      color = clamp(color + linecolor, 0.0, 1.0);
      color.a = code.a;
    }
  }
  return clamp(color + u_color_offset, 0.0, 1.0);
}
